version: "3"
services:

  backend-challenge:
    container_name: backend-challenge
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend-challenge

networks:
  backend-challenge: